# Generated by Django 5.1.3 on 2024-12-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_no',
            field=models.IntegerField(max_length=50),
        ),
    ]
